sudo: required

language: generic

services:
  - docker

env:
  - TAG=zbarcam-linux DOCKERFILE=dockerfiles/Dockerfile-linux COMMAND='. venv/bin/activate && make test'
  - TAG=zbarcam-android DOCKERFILE=dockerfiles/Dockerfile-android COMMAND='buildozer android debug'

install:
  - docker build --tag=$TAG --file=$DOCKERFILE .

script:
  # `travis_wait` also adds quotes, so we need to escape ours
  - travis_wait docker run $TAG /bin/sh -c \"$COMMAND\"
